### ISSUE TITLE
All user interface graphics should be above sprites

### ISSUE THREAD

**Issue by puzzud** [thrabchak/one-room#3]
All current user interface stuff should be at the top layer:
 - Jollyometer
 - Buttons

**Comment by puzzud** [comment]
Inadvertent fix to Jollyometer when #1 was implemented.

Buttons for like Mute and Exit still need fix.

Modal dialogs seem to be fine.

**Comment by thrabchak** [comment]
This looks fixed all around. Button group is fixed to camera. I unfixed the moon from camera to give a little sense of height.
